### ISSUE TITLE
Extremely slow typing when editing git commit

### ISSUE THREAD

**Issue by victornoel** [sd65/MiniVim#25] opened 2016-10-04 11:11 UTC
Hi,

I noticed that when I do a git commit and vim opens to write the commit, typing is really slow and laggy.
And the more there is information to show in the commit (the list of files that will be committed, the list of file ignored, etc), the more it slow and laggy!

It's really stange!

**Comment by victornoel** [comment] 2016-10-04 13:51
And this only happens if I use LANG=fr_FR.UTF8 actually! With LANG=C, it works well (and the rendering of the theme is different also).

I also timed the syntax hilighting that happened when it was slow and this is the result, so I guess it is a problem with the theme (because this does not happen without minivim):

```
 TOTAL      NOMBRE MATCH   PLUS LENT   MOYEN     NOM                MOTIF
  2   2.047940   817    0       0.010387    0.002507  gitcommitUnmergedType \t\@<=[[:lower:]][^:]*[[:lower:]]:
  3   2.044605   817    0       0.011707    0.002503  gitcommitDiscardedType \t\@<=[[:lower:]][^:]*[[:lower:]]:
  4   2.043432   817    0       0.011453    0.002501  gitcommitSelectedType \t\@<=[[:lower:]][^:]*[[:lower:]]:
  5   0.026518   817    18      0.000088    0.000032  gitcommitHeader    \%(^# \)\@<=.*:$
  6   0.018430   882    0       0.000065    0.000021  gitcommitDiff      \%(^diff --\%(git\|cc\|combined\) \)\@=
  7   0.008082   817    0       0.000032    0.000010  gitcommitAuthor    \%(^# \)\@<=\%(Author\|Committer\):
  8   0.007284   817    0       0.000039    0.000009  gitcommitNoChanges \%(^# \)\@<=No changes$
  9   0.006540   882    817     0.000025    0.000007  gitcommitComment   ^#.*
 10   0.004979   817    0       0.000019    0.000006  gitcommitNoBranch  \%(^# \)\@<=Not currently on any branch.
 11   0.004948   817    0       0.000020    0.000006  gitcommitOnBranch  \%(^# \)\@<=Your branch .\{-\} '
 12   0.004902   817    0       0.000018    0.000006  gitcommitOnBranch  \%(^# \)\@<=On branch
 13   0.004652   18     18      0.000314    0.000258  gitcommitSummary   ^.\{0,50\}
 14   0.001429   882    0       0.000010    0.000002  gitcommitWarning   ^\%(no changes added to commit\|nothing \%(added \)\=to commit\)\>.*\%$
 15   0.000758   882    0       0.000004    0.000001  gitcommitUnmerged  ^# Unmerged paths:
 16   0.000701   882    0       0.000010    0.000001  gitcommitSelected  ^# Changes to be committed:
 17   0.000693   882    0       0.000004    0.000001  gitcommitDiscarded ^# Change\%(s not staged for commit\|d but not updated\):
 18   0.000624   882    0       0.000006    0.000001  gitcommitUntracked ^# Untracked files:
 19   0.000560   882    0       0.000010    0.000001  gitcommitWarning   \%^[^#].*: needs merge$
 20   0.000516   882    18      0.000007    0.000001  gitcommitFirstLine \%^[^#].*
 21   0.000441   784    0       0.000011    0.000001  neosnippetConcealExpandSnippets <`\d\+:\=\|<{\d\+:\=\|<|
 22   0.000302   784    0       0.000001    0.000000  neosnippetExpandSnippets <`\d\+\%(:.\{-}\)\?\\\@<!`>\|<{\d\+\%(:.\{-}\)\?\\\@<!}>\|<|\d\+|>
 23   0.000012   18     0       0.000001    0.000001  gitcommitBlank     ^[^#].*
```

**Comment by sd65** [comment] 2016-10-04 20:58
Hi, thanks for this report.

However, I've never encountered this bug and can't reproduce it even with a 10.000 lines' commit message.
- Can you reproduce the lag by opening a large file with Vim ?
- How do you produce this kind of table ?

Can you open the commit message with `vim --startuptime vimstartup.log` and post the result here ?

**Comment by victornoel** [comment] 2016-10-05 07:17
Hi :)

Some more details:
- I think this has started to appear when I upgraded to Vim 8, not sure…
- I think the highlighting is broken when French is used to produce the git commit file content and this is the source of the problem (so maybe it's simply a bug in vim's gitcommit plugin, but it only lag using the theme of minivim, so maybe there is a bug in the theme… who knows ^^). When using english, the text is highlighted differently at least!
- I found they way to produce the table there: http://stackoverflow.com/questions/19030290/syntax-highlighting-causes-terrible-lag-in-vim with `:syntime`
- here is an example file to open with vim to see the problem: https://gist.github.com/victornoel/e3fd6ecbb75486b01364b6157cd8e1e5 (it MUST be named COMMIT_EDITMSG for gitcommit plugin highlighting to be applied and the problem to appear).
- the vimstartup.log is also in the gist above :)

Thanks!

**Comment by SCarSly** [comment] 2016-11-03 09:28
Hi ! I encountered this problem too. I'm running cygwin 64 with mintty and zsh. Maybe the attached profile log I made will help you.

[profile.txt](https://github.com/sd65/MiniVim/files/568537/profile.txt)

**Comment by sd65** [comment] 2016-12-03 12:23
I can reproduce the problem, thanks @victornoel. Let's the bug hunt begin !

**Comment by joeky888** [comment] 2017-03-11 05:08
I think this is a bug of vim, not minivim.

The commit message file is slow even when minivim is not loaded.

**Comment by joeky888** [comment] 2017-03-13 18:18
I've sent a bug report to the gitcommit maintainer, 

Lag happens even when I am using the color schemes of default vim.

**Comment by sd65** [comment] 2017-03-20 18:26
Theme bug confirmed. Won't fix except if this append often.
Thanks for the report nevertheless!

**Closed as completed by sd65** 2017-03-20 18:26 UTC
