### ISSUE TITLE
Simplify the addition of custom configuration

### ISSUE THREAD

**Issue by victornoel** [sd65/MiniVim#20] opened 2016-06-01 07:50 UTC
Since most user clone the minivim repository, when they want to add their own custom configuration (either tweaking the minivim configuration or separate things), they need to modify the version controlled file.

It would be great if minivim by default would recognize an extra file (and ignore if it isn't present) where to put such custom configuration.

Maybe it would be best if it was in the .vim/ directory, not sure :)

**Comment by sd65** [comment] 2016-06-01 20:31
Duplicate of #19. :+)

**Closed as completed by sd65** 2016-06-01 20:31 UTC
Labels: duplicate
