### ISSUE TITLE
new feacture - Paste

### ISSUE THREAD

**Issue by azlux** [sd65/MiniVim#18] opened 2016-03-24 09:12 UTC
Hi,
Do there are a way to paste with ctrl-V, when a read the conf, I suppose it's not difficult, but can you add `:set paste` and `:set nopaste` before and after the paste to remove indent because code i lot of the time already indent

Thank
(your work is awesome)

**Comment by sd65** [comment] 2016-03-29 13:23
Thanks !
Duplicate of #13, I answer there.

**Closed as completed by sd65** 2016-03-29 13:23 UTC

**Comment by sd65** [comment] 2016-03-29 13:31
By the way, I think we should not remap Ctrl-V as it enters the visual block mode, which is useful!
